kind: Service
apiVersion: v1
metadata:
  name: searce-sandbox
spec:
  selector:
    app: searce-sandbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: searce-sandbox
  labels:
    app: searce-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searce-sandbox
  template:
    metadata:
      labels:
        app: searce-sandbox
    spec:
      containers:
      - name: searce-sandbox
        image: gcr.io/searce-sandbox/hemil-nodejs-trial
        resources:
          limits:
            cpu: "0.4"
          requests:
            cpu: "0.2"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
